[project]
name = "shedding-hub"
version = "0.2.0"
readme = "README.md"
description = "Data and statistical models for biomarker shedding."
dependencies = [
    "pyaml",
    "requests",
    "pandas",
    "matplotlib",
    "numpy",
    "scipy"
]

[tool.setuptools.packages]
find = {}

[tool.setuptools.package-data]
shedding_hub = ["data/*.yaml"]
