name: Shedding Hub

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Lint code
        run: black --check .
      - name: Run tests
        run: pytest -v --cov=shedding_hub --cov-report=term-missing
      - name: Run doctests
        run: python -m doctest -o ELLIPSIS -o NORMALIZE_WHITESPACE README.md
      - name: Build package
        run: python -m build
      - name: Validate package
        run: twine check dist/*.tar.gz dist/*.whl
