name: Summarize Changes

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: pip
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Create summary for changed files
        id: changes-comment
        # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#setting-an-output-parameter
        run: echo "stdout=`python .github/workflows/summarize.py`" >> $GITHUB_OUTPUT
      - name: Add PR comment if changes are available
        uses: mshick/add-pr-comment@v2
        if: steps.changes-comment.outputs.stdout
        with:
          message: |
            ${{ steps.changes-comment.outputs.stdout }}
